force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Store ipad and storage locations
used in item definition</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>iPad</fullName>
                <default>true</default>
                <label>iPad</label>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InventoryManagerControllerTest.cls
@isTest
private class InventoryManagerControllerTest {
    
	@istest
    private static void getSetttings_positive(){
        Map<String, Boolean> settings = InventoryManagerController.getSettings();
        System.debug(settings);
        System.assert(settings.containsKey('invmgrnp__Log_Item_Actions'));
    }
	@istest
    private static void getUserSetttings_positive(){
        Location__c location = new Location__c();
        location.Name = 'Door';
        location.Location_Type__c = 'iPad';
        location.Assigned_User__c = UserInfo.getUserId();
        insert location;

        Map<String, String> userSettings = InventoryManagerController.getUserSettings();
        
        System.assertEquals(true,userSettings.containsKey('Location'));
    }
    
	@istest
    private static void getUserSetttings_negative(){
        Location__c location = new Location__c();
        location.Name = 'Door';
        location.Location_Type__c = 'iPad';
        //location.Assigned_User__c = UserInfo.getUserId();
        insert location;

        
        Map<String, String> userSettings = InventoryManagerController.getUserSettings();
        
        
        System.assertEquals(true,userSettings.containsKey('Location'));
        System.assertEquals(null,userSettings.get('Location'));
    }
}