force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <description>Abstract version of an Item</description>
    <label>Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Deactivate an item so it disappears from UI rather than deleting it. Deletion will leave orphan items</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Item Category</description>
    <inlineHelpText>Select an Item Category</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A - Other</fullName>
                <default>true</default>
                <label>N/A - Other</label>
            </value>
            <value>
                <fullName>Medical Supplies</fullName>
            </value>
            <value>
                <fullName>Sanitary Supplies</fullName>
            </value>
            <value>
                <fullName>Clothing</fullName>
            </value>
            <value>
                <fullName>Paper Plates</fullName>
            </value>
            <value>
                <fullName>Snack Foods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantity of items in inventory</description>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>Type and SubType (eg Diapers Small)</description>
    <formula>IF(ISBLANK(SubType__c),Type__c,Type__c  &amp; &#39; - &#39; &amp; SubType__r.Name)</formula>
    <inlineHelpText>Type and SubType (eg Diapers Small)</inlineHelpText>
    <label>Name/Nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <description>Description of the item</description>
    <inlineHelpText>Description of the item (i.e. Pampers Diapers, Size 3, Quantity 20)</inlineHelpText>
    <label>Item Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <description>Item Sub Categroy</description>
    <inlineHelpText>Item Sub Category</inlineHelpText>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>N/A Other</fullName>
                <default>true</default>
                <label>N/A Other</label>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Diapers</fullName>
            </value>
            <value>
                <fullName>Shirts</fullName>
            </value>
            <value>
                <fullName>Pants</fullName>
            </value>
            <value>
                <fullName>Underwear</fullName>
            </value>
            <value>
                <fullName>Gloves</fullName>
            </value>
            <value>
                <fullName>Socks</fullName>
            </value>
            <value>
                <fullName>Deodorant</fullName>
            </value>
            <value>
                <fullName>Toothpaste</fullName>
            </value>
            <value>
                <fullName>Toothbrushes</fullName>
            </value>
            <value>
                <fullName>Combs</fullName>
            </value>
            <value>
                <fullName>Adult Blouses</fullName>
            </value>
            <value>
                <fullName>Child Clothes</fullName>
            </value>
            <value>
                <fullName>Baby Wipes</fullName>
            </value>
            <value>
                <fullName>Baby Bottles</fullName>
            </value>
            <value>
                <fullName>Sealed snack food</fullName>
            </value>
            <value>
                <fullName>Gift cards to purchase food items</fullName>
            </value>
            <value>
                <fullName>Phone cards</fullName>
            </value>
            <value>
                <fullName>Plastic bags</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubType</label>
    <referenceTo>SubType__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Name of the item (i.e. Pampers)</description>
    <inlineHelpText>Name of the item</inlineHelpText>
    <label>Type</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Store ipad and storage locations
used in item definition</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubType__c/SubType__c.object-meta.xml
<CustomObject>
    <description>Used to store attributes such as size or quantity type</description>
    <label>SubType</label>
    <nameField>
        <label>SubType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ItemController.cls
public with sharing class ItemController {
    //This will be used to check if we should show All items even if location is not assigned a user.
    //This will be used via Test class
	@TestVisible private static Boolean showAllItemsTestOverride = false;
    Private static Boolean showAllItems = false;
    
    //Return all Active items which belong a location enabled for current logged in user
    //Use automatic session info rather than manually provided location
    //Make sure to only get items which are active
    @AuraEnabled(cacheable=true)
    public static List<Item__c> getItemList() {
        List<Item__c> itemList = new List<Item__c>();
        try{
            Map<String, Boolean> inventoryManagerSettings = InventoryManagerController.getSettings();            
            
            showAllItems = (inventoryManagerSettings.containsKey('invmgrnp__Show_Items_in_Locations_without_User') && inventoryManagerSettings.get('invmgrnp__Show_Items_in_Locations_without_User') == true)?True:false;
            if(Test.isRunningTest() && (showAllItems != showAllItemsTestOverride)){
                showAllItems = showAllItemsTestOverride;
            }
            //If show all items true then search for location with null assigned user as well as current running user
            //If not then only show items assigned to curent user
            if(showAllItems){
                itemList =
                    [SELECT Id, Name, Category__c, Count__c, Item_Description__c, Location__c, Location__r.Name,
                        Display_Name__c, Sub_Category__c, SubType__c, Type__c
                    FROM Item__c
                    WHERE Active__c = true and Location__c in (select id from Location__c where Assigned_User__c=:UserInfo.getUserId() or Assigned_User__c=null)
                    WITH SECURITY_ENFORCED
                    ORDER BY Display_Name__c
                    ];
            }else{
                itemList = [SELECT Id, Name, Category__c, Count__c, Item_Description__c, Location__c, Location__r.Name,
                            Display_Name__c, Sub_Category__c, SubType__c, Type__c
                        FROM Item__c
                        WHERE Active__c = true and Location__c in (select id from Location__c where Assigned_User__c=:UserInfo.getUserId())
                        WITH SECURITY_ENFORCED
                        ORDER BY Display_Name__c
                        ];
            }

        }catch(System.QueryException e){Util.log('ItemController:getItemList():System.QueryException' + e.getMessage());
        }catch(Exception e){Util.log('ItemController:getItemList():Exception' + e.getMessage());
        }
        return itemList;
    }
}