force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <description>Abstract version of an Item</description>
    <label>Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Deactivate an item so it disappears from UI rather than deleting it. Deletion will leave orphan items</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantity of items in inventory</description>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Name of the item (i.e. Pampers)</description>
    <inlineHelpText>Name of the item</inlineHelpText>
    <label>Type</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Store ipad and storage locations
used in item definition</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ItemControllerTest.cls
@istest
public  class ItemControllerTest {
    @TestSetup
    static void makeData(){
        
        Location__c loc = new Location__c();
        loc.Name = 'Location 1';
        loc.Assigned_User__c = UserInfo.getUserId();
        insert loc;
        
        List<Item__c> items = new List<Item__c>();
        for(Integer i=0; i<10; i++){
            Item__c item = new Item__c();
            item.Type__c = 'Item Name ' + i;
            item.Location__c = loc.Id;
            item.Count__c = 1;
            item.Active__c = true;
            items.add(item);
        }
        insert items;
    }
    @isTest
    private static void getItemList_positive(){
        List<Item__c> items = ItemController.getItemList();
        System.assertEquals(10, items.size());
    }
}