force-app/main/default/objects/Inventory_Manager__mdt/Inventory_Manager__mdt.object-meta.xml
<CustomObject>
    <label>Inventory Manager</label>
    <pluralLabel>Inventory Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inventory_Manager__mdt/fields/isEnabled__c.field-meta.xml
<CustomField>
    <fullName>isEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if this record is enabled</description>
    <label>isEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Store ipad and storage locations
used in item definition</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InventoryManagerController.cls
//Class to get configuration data for Inventory manager
public with sharing class InventoryManagerController {
    //Get list of records in "Inventory Manager" custom metadata type
    @AuraEnabled(cacheable=true)
    public static Map<String, Boolean> getSettings() {
        Map<String, Boolean> inventoryManagerSettings = new Map<String, Boolean>();
        try{
            for(Inventory_Manager__mdt record: [SELECT QualifiedApiName, isEnabled__c FROM Inventory_Manager__mdt]) {
                inventoryManagerSettings.put(record.QualifiedApiName, record.isEnabled__c);
            }
        }catch(Exception e){Util.log('InventoryManagerController:getSettings():Exception' + e.getMessage()); }
        

        return inventoryManagerSettings;
    }

    //Get list of records in "Inventory Manager" custom metadata type
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getUserSettings() {
        Map<String, String> userSettings = new Map<String, String>();

        try{
            Location__c location = [select id from Location__c where Assigned_User__c=:UserInfo.getUserId()];
            userSettings.put('Location', location.Id);
        }catch(Exception e){ userSettings.put('Location', null); }

        return userSettings;
    }

}